version: '3.8'

services:
  source-safe-database-dev:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: source-safe
    container_name: db

  source-safe-backend-dev:
    build:
      context: .
      dockerfile: ./backend/source-safe/Dockerfile.dev
    container_name: source-safe-backend-dev
    # environment:
    #     PORT: ${PORT}
    ports:
      - '3009:3009'
    depends_on:
      - source-safe-database-dev
    volumes:
      - ./backend/source-safe/src:/backend/src

  source-safe-frontend-dev:
    build:
      context: .
      dockerfile: ./frontend/files-managment/Dockerfile.dev
    container_name: source-safe-frontend-dev
    # environment:
    #     PORT: ${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - source-safe-backend-dev
    volumes:
      - ./frontend/files-managment/src:/frontend/src
      - ./frontend/files-managment/app:/frontend/app

  source-safe-pgadmin-dev:
    image: dpage/pgadmin4
    restart: always
    container_name: source-safe-pgadmin-dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4 
    ports:
      - '5050:80'
    depends_on:
      - source-safe-database-dev